### ISSUE TITLE
Feature: Devices

### ISSUE THREAD

**Issue by marcobiedermann** [PeterPanen/storybook-addon-scissors#4]
I suggest using the device list from Google Devtools:
https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/emulated_devices/module.json

Also it would be nice to have an option for device-pixel-ratio.

**Comment by PeterPanen** [comment]
@marcobiedermann Thats pretty cool, iv never thought about using those.
Thanks for the suggestion, i could definitely try to make that an option.

**Comment by marcobiedermann** [comment]
@PeterPanen 
Cool, you just have to change mapping of the device properties.
I would go for the Google Devtools devices because they are more up to date if you ask me.
Making both options work at the same time makes things inconsistant.
Still the user has the option to specify other devices, as long as he / she follows the schema.
Maybe you could add a boilerplate schema to the docs.
