### ISSUE TITLE
Dropdown border issue - The border bottom wont appear till we scroll down to the last dropdown element.

### ISSUE THREAD

**Issue by Madhusudhan-Srinivas** [PeterPanen/storybook-addon-scissors#6]
![screenshot_3](https://user-images.githubusercontent.com/36559494/44584916-28867b80-a7c8-11e8-80ce-9288cd3ad20e.png)

![screenshot_4](https://user-images.githubusercontent.com/36559494/44584947-3e943c00-a7c8-11e8-8635-7f760d7d4238.png)

**Comment by PeterPanen** [comment]
Sorry for the late response, i somehow missed the notification of this issue.
Is this a clean install of Storybook? Or do you run your own webpack config?
I notice a JSX tab, is this the addon-jsx?

**Comment by PeterPanen** [comment]
@Madhusudhan-Srinivas I just did a clean Storybook and installed both scissors and the jsx addon, and i dont notice any problems.

Maybe you can describe how to reproduce your bug?

**Comment by Madhusudhan-Srinivas** [comment]
@PeterPanen First of all I want to say that it's an very useful plugin to storybook, Let me reinstall storybook along with scissors, jsx addon  and get back to you.
Thank you.

**Comment by Madhusudhan-Srinivas** [comment]
@PeterPanen  First of all I want to say that it's an very useful plugin to storybook, Let me reinstall storybook along with scissors, jsx addon and get back to you.
Thank you.
